### ISSUE TITLE
Forward events

### ISSUE THREAD

**Issue by tobiasklemp** [vincjo/svelte-simple-datatables#13]
Hi,
I really like the datatable, but i think it would be great if there are some forwarded events like pagination change, or even better export a prop to bind to the page number. Same thing with search functionalty. 

Or is there any other way to handle async data? As far as i can tell i have to get all of the data from the server at once, because I dont know when to load the data for the next page.

**Comment by vincjo** [comment]
Hi,
For the moment I'm affraid that pagination and async data are incompatible.
Something is planned in this direction but I don't know when it can be delivered.

**Comment by Hmerman6006** [comment]
Any movement on this?  I tried accessing elements using `querySelector` and add events to the `input[type="text"]`, but it did not work.
