### ISSUE TITLE
Table height is incorrect

### ISSUE THREAD

**Issue by mcmxcdev** [vincjo/svelte-simple-datatables#16]
My table height gets rendered to `height: 88px;` no matter how many rows I have and therefore is unusable as can be seen in the screenshot.

I compared the css styling of https://vincjo.fr/svelte-simple-datatables/#/demo with the table in my project and it seems that in your example the height calculation for the article wrapper works, it is `<article class="dt-table" style="height: 344px; overflow-x: auto;">`

![Screenshot from 2020-12-11 16-26-28](https://user-images.githubusercontent.com/16797721/101921939-d4d51180-3bcd-11eb-99e7-e6df19ac53ee.png)

**Comment by vincjo** [comment]
The height of the table is calculated from the computed height of the parent element.
By default the Datatable is first rendered with a minimum height of 160px, then it fits to the container.

2 options:
- define a height for the ````div```` containing the Datatable
- disable Scroll Y in the settings ([demo](https://vincjo.fr/svelte-simple-datatables/#/demo/scroll-y))

**Comment by mhatvan** [comment]
For now I have `scrollY` disabled yes, but I would like to use it.

Defining a height for the outer div is not a useful solution for me: I cannot know how many rows will be fetched from the backend and if any at all. With a fixed height I would have a e.g. 500px table container without any content...
