### ISSUE TITLE
Bootstrap support?

### ISSUE THREAD

**Issue by gerald-dotcom** [vincjo/svelte-simple-datatables#2]
This is a great library but it overflow the layout on my screen. I'm not a CSS wizard either, just I love the grid layout that's it.

**Comment by gerald-dotcom** [comment]
Just used your example CSS and everything fit fine but I think still not responsive enough to view on mobile screens. Again, this is a great lib and I think perhaps one and only lib for Sv

**Comment by vincjo** [comment]
Thanks for your feedback. There is responsive support in version 0.1.16 ([demo](https://vincjo.fr/svelte-simple-datatables/#/demo/responsive)).
I haven't tested the component in a grid layout yet but will do so soon

**Comment by vincjo** [comment]
Integration in a grid layout should work correctly from v0.1.17
[CSS Grid test](https://vincjo.fr/svelte-simple-datatables/#/test)

**Comment by gerald-dotcom** [comment]
Thanks for fixing these. There were few more issues I found but forget to mention. 

Searching under column like Email when there is large amount data doesn't seems yield results altho it work fine for smaller amount of data

Sometimes searching under column causes overflow and causes to expand the table out of page.
