### ISSUE TITLE
Data get hidden/underflowen

### ISSUE THREAD

**Issue by gerald-dotcom** [vincjo/svelte-simple-datatables#3]
If table only has 1 entry, the data get hidden due to height. Of course, the table may need to contain for example 11 columns and IDs like "7d440900-9017-4563-e6ea-8a2998b0a18a"

If you can fix this out, It would be great..

**Comment by gerald-dotcom** [comment]
Strange thing is when I go to diff page then come back to that page, the data get appear. Whatever, it does shows 1 entry every time whether I on or back so it means it has data both times but some bug maybe who knows.

**Comment by vincjo** [comment]
Thanks for your feedback. There was a bug with the horizontal scrollbar height
This should be fixed in v0.1.15 : [ScrollX demo](https://vincjo.fr/svelte-simple-datatables/#/demo/scroll-x)
