### ISSUE TITLE
`Identifier 'global' has already been declared` when using SvelteKit due to outdated version on npm registry

### ISSUE THREAD

**Issue by nooreldeensalah** [vincjo/svelte-simple-datatables#36]
> __Edit (August-30@4:26 PM UTC)__
> I've managed to resolve this issue by installing the repository build directory using `npm install vincjo/svelte-simple-datatables`.
-------------------------
Hi,

I've tried this library, and it's great, but I've tried using it with SvelteKit and it's not working due to the following error `Identifier 'global' has already been declared`:
![image](https://user-images.githubusercontent.com/61914159/131265971-6ff8d680-ad70-4649-b759-74ccc6d1ef28.png)

I've found an issue #29 and a PR #30 addressing this bug, but I'm using the latest npm version and I got this bug, I've installed the library as a dev-dependency as instructed.

Any help would be appreciated.

Thanks,

**Comment by nooreldeensalah** [comment]
The PR changes don't seem to be added to the library code.

This image is from the latest npm version
![image](https://user-images.githubusercontent.com/61914159/131266175-5795ed60-88db-4ceb-975d-d6b74e90686c.png)

**Comment by nooreldeensalah** [comment]
I managed to resolve this issue by installing the repository build directory using `npm install vincjo/svelte-simple-datatables`.

I'll rename this issue to be more accurate, then close it.

**Comment by nooreldeensalah** [comment]
Well, I thought it would be better to re-open the issue, because I realized someone else using SvelteKit might stumble upon this bug, so until the npm registry is updated, I'll keep this issue open.

**Comment by vincjo** [comment]
Changed as "globalFilter" identifier
