### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by GHesericsu** [vincjo/svelte-simple-datatables#41]

**Comment by damevin** [comment]
Up 👋

**Comment by vincjo** [comment]
Hello,

My bad... 
Just took a VPS today it should be online in few days. I hope this week.
I don't think i could use GH page cause i need to launch  ``npm build`` somewhere

**Comment by vcheeze** [comment]
@vincjo seems to be down again 😢

**Comment by melMass** [comment]
> I don't think i could use GH page cause i need to launch  ``npm build`` somewhere

That's exactly how GH pages work! You enable CI on the repo, and the CI should output (using `npm build` in your case) to a `public` folder at the root of the repo, that's what get statically deployed.
It the best option IMO, it's free, auto deployed on change etc...

**Comment by vincjo** [comment]
Finally, the demo site is available again :satisfied:
