### ISSUE TITLE
Error after installing & setting up 

### ISSUE THREAD

**Issue by mordreds** [vincjo/svelte-simple-datatables#5]
**After installing and following the setup guide carefully i still get ERROR below :: What am i not doing right ??**  

Datatable is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

![image](https://user-images.githubusercontent.com/32673874/94378164-c0c55c00-0116-11eb-9a39-dfd5e19a2b34.png)

**Comment by vincjo** [comment]
There is no SSR support at this time.
It must be installed in DevDependancies. 

npm i **-D** svelte-simple-datatables

Then it will be compiled with the app
https://github.com/sveltejs/sapper-template#using-external-components
