### ISSUE TITLE
Initital sort

### ISSUE THREAD

**Issue by FlashPapa** [vincjo/svelte-simple-datatables#51]
Hi !
How can i set a default sort 'desc' on initialization ?
Thanks

**Comment by vincjo** [comment]
Hello,

It is not possible for now... :confused:

I will develop an API to manage tables programmatically (I hope for sometime in September). But for the moment it is not possible.

In the meantime, you can order the JSON before sending it to datatable, or directly in the SQL query... 
It's not very flexible

**Comment by FlashPapa** [comment]
Ok, no problem @vincjo, 
I do a _.reverse(data) before for the moment :smirk:
Thanks
