### ISSUE TITLE
Disable floating header and 'fit to container'

### ISSUE THREAD

**Issue by MattPurland** [vincjo/svelte-simple-datatables#7]
I would like the datatable to act more like a standard table, so no floating header or size constraints based on the container. Can this be added?

**Comment by MattPurland** [comment]
Just figured out I could do this with some hacky CSS:

`.datatable {
    height: auto !important;

    .dt-table {
        height: auto !important;
    }
}`

**Comment by MattPurland** [comment]
Reopening as I believe it's probably a good idea to do this properly using a setting as I'm having issues with how the floating header renders its column widths

**Comment by vincjo** [comment]
I'm thinking of an elegant way to handle this use case.
Thanks for your feedback

**Comment by MattPurland** [comment]
Thanks, I might take a look myself and submit a PR if that helps/I can find time

**Comment by vincjo** [comment]
This could be set with an option like ````scrollY: false````
The table would then be drawn in a standard way without a floating header.

A lot of javascript avoided with that option.
I keep you informed here

**Comment by vincjo** [comment]
New setting to disable the floating header: ````{ scrollY: false }````
At the same time it removes the "fit to conatainer" feature

There is a limitation on filtering columns so I created an optionnal ````<ColumnFilterInputs/>```` component.

Demo : [ScrollY](https://vincjo.fr/svelte-simple-datatables/#/demo/scroll-y)

**Comment by MattPurland** [comment]
This is great, thanks.

The only issue I can see (so far) is that when sorting, the 'asc' or 'desc' class isn't removed from previous columns unless you click on a new sorting column twice

**Comment by vincjo** [comment]
Indeed, this has been fixed in 0.1.25
