### ISSUE TITLE
Disable all/some CSS

### ISSUE THREAD

**Issue by MattPurland** [vincjo/svelte-simple-datatables#8]
Would it be possible to have a setting to disable CSS? For example I'd like complete control over the styling (borders, margin, height/width, etc), but not any CSS that's required for functionality, like layout and positioning.

**Comment by vincjo** [comment]
To disable CSS there is a new setting : ````{ css: false }````
I made some style examples to help with customization.

Demo: [CSS](https://vincjo.fr/svelte-simple-datatables/#/demo/css)

**Comment by MattPurland** [comment]
Perfect, thanks
